### PR TITLE
Information about Kubernetes, Helm, and Longhorn

### PR DESCRIPTION
**Pull request by jameswynn**
I added the following sections:
* Installation with Helm
* Configuration of Kubernetes cluster, along with service discovery
* Kubernetes Widget
* Longhorn Widget

### CODE REVIEW

**Comment by shamoon** [comment]
Awesome thank you! Mind re-basing to this branch?

**Comment by jameswynn** [comment]
Well, I did that wrong. Let me try this again...

**Comment by shamoon** [comment]
No worries if it’s giving you drama 😄 I can do it too

**Comment by jameswynn** [comment]
Fixed.

**Pull request merged**
