### PR TITLE
Add UDM-Pro instructions

### PR DESCRIPTION
**Pull request by CambridgeComputing**
Added an example config for pulling stats on a v3+ firmware UDM-Pro as the default one does not work as-is.

### CODE REVIEW

**Comment by shamoon** [comment]
Hmm, do you have any documentation to support this? I am running UDM Pro v3.1.15 and this is not my experience and no one has reported it (many users use our UniFi widgets so tbh, I think we would have heard).

Homepage actually tries to detect the console type and choose the endpoint from there. For me, all I have in the url is the local IP address of my UDMP `https://10.0.1.1`, that hasn't changed in a long time even through my upgrade to v3...

**Comment by CambridgeComputing** [comment]
Strange, and apologies if I missed something! In my testing, using the URL `https://192.168.1.1` gives me a 404:
unifi1

Switching this to `https://192.168.1.1/proxy/network` fixes the issue for me:
unifi2

As well, trying to use port 8443 also fails for me; I just tried that as it was recommended is some older Unifi API guides.

If the root issue here is that there's a script that is supposed to be detecting if it's communicating with a Cloud Key or a UDM, I can look into it that as well - any pointers would be appreciated. What I've proposed in the documentation is essentially a good workaround for now (at least for me).

Thank you for helping to maintain this great project! I hope I can help further in any way possible.

**Comment by shamoon** [comment]
Hmm, yea the code does try to detect udmp and if it is it tacks on that 'prefix':

https://github.com/benphelps/homepage/blob/fc7e73eba274d81213d74195ae87d9a1099d9948/src/widgets/unifi/proxy.js#L11

https://github.com/benphelps/homepage/blob/fc7e73eba274d81213d74195ae87d9a1099d9948/src/widgets/unifi/proxy.js#L77-L87

The way it 'detects' if it's talking to a udmp is it pings the top level URL and looks for a `x-csrf-token` header (non-udmp dont seem to send this) e.g. if you run `curl -L --insecure -i https://192.168.1.1` do you see that header returned? For example I get:

```bash
...
content-type: text/html; charset=utf-8
content-length: 818
x-csrf-token: e34fdb12-0997-bch4-husb-c80914f8fa55
x-response-time: 3ms
...
```

**Comment by CambridgeComputing** [comment]
Here is the output from the above curl command against my UDM Pro:
```
$ curl -L --insecure -i https://192.168.1.1

HTTP/2 200
vary: Origin
x-dns-prefetch-control: off
expect-ct: max-age=0
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=15552000; includeSubDomains
x-download-options: noopen
x-content-type-options: nosniff
x-permitted-cross-domain-policies: none
referrer-policy: no-referrer
x-xss-protection: 0
accept-ranges: bytes
content-type: text/html; charset=utf-8
content-length: 818
x-csrf-token: b9d911d7-bde6-4a7b-b908-ce217036f59b
x-response-time: 4ms
set-cookie: TOKEN=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT; samesite=none; secure; httponly
date: Mon, 28 Aug 2023 05:17:39 GMT

<!doctype html><html lang="en"><head><meta charset="utf-8"><link rel="icon" href="/favicon.ico?v3" sizes="any"><link rel="icon" href="/favicon.svg?v3" type="image/svg+xml"><link rel="apple-touch-icon" href="/apple-touch-icon.png?v3"><title>UniFi OS</title><meta name="viewport" content="width=device-width,initial-scale=1"><script>window.UNIFI_OS_MANIFEST = {"model":{"id":"UDMPRO","shortName":"UDM Pro","longName":"UniFi Dream Machine Pro"},"images":{"small":"/assets/images/small.png?udmpro-2.0.0","medium":"/assets/images/medium.png?udmpro-2.0.0","large":"/assets/images/large.png?udmpro-2.0.0","huge":"/assets/images/huge.png?udmpro-2.0.0"}}</script><script defer="defer" src="/main.df9088bb8c1a96f7ddf6.js"></script><link href="/main.0e9197a3.css" rel="stylesheet"></head><body><div id="root"></div></body></html>
```

So yes, mine does show that token. I'll play around with the code and see if there is anything specific to my setup that's causing it not to trigger the UDM Pro API detection. I also figured I'd include the full curl response here in case you spot something quicker than I do. Thanks for the pointer!

**Pull request closed without merging**
