### PR TITLE
Update settings.md

### PR DESCRIPTION
**Pull request by sankethguru**

### CODE REVIEW

**Comment by shamoon** [comment]
I think it is `favicon` https://github.com/benphelps/homepage/blob/e3d60297bcd61da5dd33656829e3ac7e677d1e25/src/pages/index.jsx#L221

**Comment by sankethguru** [comment]
@shamoon , 
This works:
       icon: https://img.icons8.com/small/512/disney-hotstar.png
But this doesn't:
       favicon: https://img.icons8.com/small/512/disney-hotstar.png

**Comment by shamoon** [comment]
Not sure whats up for you, but this is with `favicon: https://img.icons8.com/small/512/disney-hotstar.png`
Untitled

**Comment by sankethguru** [comment]
Apologies. Misunderstood the icon to be for the services. favicon is for the Homepage tab icon! Apologies.

**Pull request closed without merging**
