### PR TITLE
Update k8s.md for traefik support in clusterrole binding

### PR DESCRIPTION
**Pull request by hugosxm**

### CODE REVIEW

**Comment by shamoon** [comment]
I dont use k8s. Presumably this would be an optional thing though?

**Comment by hugosxm** [comment]
This is required only if you want to use the traefik ingressroute auto discovery mecanism

**Comment by shamoon** [comment]
Right, so does this belong in the general docs? Seems to only apply in a specific use case…

**Comment by hugosxm** [comment]
maybe we could add this in the "Traefik IngressRoute support" ?

**Comment by shamoon** [comment]
I guess, is there a request out there from someone to know how to do this? It just feels a little out-of-left-field...

**Comment by santimar** [comment]
I am using k3s (which uses traefik by default) and I had to spend some time before find this issue.
On the main documentation seems that Traefik support is out of the box, but this is only true if one install Homepage via the unofficial helm package (listed in the [docs as well](https://gethomepage.dev/en/installation/k8s/#install-with-helm))
Since the unofficial package already [support this](https://github.com/jameswynn/helm-charts/blob/main/charts/homepage/templates/rbac.yaml#L44), I think this should be merged

**Pull request merged**
